### ISSUE TITLE
Failed when build

### ISSUE THREAD

**Issue by YLaido** [kizure/Accelerider.Web.pan#1]
https://github.com/kizure/Accelerider.Web.pan/blob/5a9f93b3833632ef36d4806a5cd19eb84dee632f/src/libs/cryptos.js#L1

should be `import MD5 from 'crypto-js/md5'`
Platform: Ubuntu 14.04 x64

Great project btw. Cheers. :)

**Comment by ca1e** [comment]
thx for the issue,i'v never build it on ubuntu or similar OS before.
